name: Build Installer

on:
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Configure and build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build --config Debug

    - name: Download and install Inno Setup
      run: |
        Invoke-WebRequest -Uri https://jrsoftware.org/download.php/is.exe -OutFile is.exe
        Start-Process is.exe -ArgumentList "/VERYSILENT", "/DIR=C:\InnoSetup" -Wait

    - name: Run Inno Setup Compiler
      run: |
        "C:\InnoSetup\ISCC.exe" installer.iss

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: HelloAppInstaller
        path: installer\HelloAppInstaller.exe
